# Starter pipeline
 # Start with a minimal pipeline that you can customize to build and deploy your code.
 # Add steps that build, run tests, deploy, and more:
 # https://aka.ms/yaml
 trigger:
  batch: "true"
 pr:
  autoCancel: "true"
  branches:
     include:
     - master
  paths:
     exclude:
     - README.md
     - azure-pipelines.yml
 jobs:
 - job: DeployVSCodeToDevOps
   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
   steps:
     - task: UseNode@1
       inputs:
         version: '12.0.0'
     - bash: 
         npm install n latest sfdx-cli --global
       displayName: Install Salesforce CLI
     - bash: 
         sfdx force:auth:jwt:grant --clientid $(org1ClientID) --jwtkeyfile ./buildfiles/server.key --username $(org1UserName) --instanceurl $(org1InstanceURL) -a devOrg
       displayName: Authorize salesforce org
     - bash: 
         sfdx force:source:convert -r ./force-app -d ./toDeploy
       displayName: Convert to deploy source
    #  - bash: 
    #      sfdx force:mdapi:deploy -l RunLocalTests -c -d ./toDeploy -u devOrg -w 10
    #    displayName: Run validation on source code
     - bash: 
         sfdx force:mdapi:deploy -d ./toDeploy -u devOrg -w 10
       displayName: Deploy source code to Dev Org
